baseURL = "https://www.nistu.de/"
title = "nistude"
theme = "coder"
languageCode = "de"
defaultContentLanguage = "de"
rssLimit = 1
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[params]
  author = "Nikolay Sturm"
  info = "Multi-Ontology Sense-Making"
  description = "Nikolay Sturm's private Webseite"
  keywords = "cynefin,strategie,geld,finanzen,investieren"
  avatarurl = "images/nikolay.jpg"
  colorscheme = "dark"

  [[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/nistude/"

  [[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/nistude/"

  [[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/nikolay-sturm-13459b3/"

  [[params.social]]
    name = "Xing"
    icon = "fab fa-xing"
    weight = 4
    url = "https://www.xing.com/profile/Nikolay_Sturm/"

  [[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 5
    url = "index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[menu]

  [[menu.main]]
    name = "Blog"
    weight = 1
    url = "/posts/"

  [[menu.main]]
    name = "Über mich"
    weight = 2
    url = "/about/"

  [[menu.main]]
    name = "Impressum"
    weight = 3
    url = "/impressum/"

[privacy]

  [privacy.disqus]
    disable = true

  [privacy.googleAnalytics]
    disable = true

  [privacy.instagram]
    disable = true

  [privacy.twitter]
    disable = true

  [privacy.vimeo]
    disable = true

  [privacy.youtube]
    disable = true
